### ISSUE TITLE
Test django-splash on Python 3.11

### ISSUE THREAD

**Issue by feanil** [openedx/django-splash#175]
This repository is a depedency of edx-platform and needs to be upgraded to Python 3.11 before
the Readwood release is cut (mid-April).

~~- [ ] Requirements are compiled with Python 3.8~~
~~- [ ] Tests are run on Python 3.8 and 3.11~~
~~- [ ] (Optional) Tests are also run with 3.12 and passing or 3.12 issues are ticketed.~~
~~- [ ] Classifiers in setup.py setup.cfg or pyproject.toml indicate Python 3.11 support~~
~~- [ ] A new version is release to PyPI~~
~~- [ ] A PR is merged to edx-platform to use the new version~~

- [ ] Finish the [django-splash DEPR](https://github.com/openedx/public-engineering/issues/224) instead.

**Comment by ormsbee** [comment]
I wrote this in the [django-splash PR](https://github.com/openedx/django-splash/pull/170), but django-splash [should be archived](https://github.com/openedx/public-engineering/issues/224) and instead of upgraded.
